-- Stable player identity dictionary.
--
-- This migration is additive. It does not modify canonical player_id values
-- in existing ETL or app-facing tables.
--
-- After applying the DDL, run sync_player_identity_dictionary() from
-- etl/player_identity_dictionary.R. etl_full() runs that sync automatically
-- before correction loading and after each successful base-table iteration.

CREATE TABLE IF NOT EXISTS basketball_test.player_identities (
  identity_id bigint GENERATED BY DEFAULT AS IDENTITY
    (START WITH 1000000000000) PRIMARY KEY,
  identity_key text NOT NULL UNIQUE,
  display_name text NOT NULL,
  first_name text,
  last_name text,
  first_name_local text,
  last_name_local text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS basketball_test.player_identity_map (
  map_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider text NOT NULL DEFAULT 'segev',
  game_year int NOT NULL,
  team_id int NOT NULL,
  game_id int,
  source_player_id int NOT NULL,
  identity_id bigint NOT NULL
    REFERENCES basketball_test.player_identities(identity_id),
  canonical_player_id int NOT NULL,
  scope text NOT NULL CHECK (scope IN ('season', 'game')),
  active boolean NOT NULL DEFAULT true,
  player_name text,
  reason text,
  evidence text,
  mapping_origin text NOT NULL DEFAULT 'manual',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (
    (scope = 'season' AND game_id IS NULL) OR
    (scope = 'game' AND game_id IS NOT NULL)
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS player_identity_map_season_key
  ON basketball_test.player_identity_map
  (provider, game_year, team_id, source_player_id)
  WHERE game_id IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS player_identity_map_game_key
  ON basketball_test.player_identity_map
  (provider, game_id, team_id, source_player_id)
  WHERE game_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS player_identity_map_identity_idx
  ON basketball_test.player_identity_map (identity_id)
  WHERE active;

CREATE INDEX IF NOT EXISTS player_identity_map_canonical_idx
  ON basketball_test.player_identity_map
  (provider, game_year, team_id, canonical_player_id)
  WHERE active;

CREATE OR REPLACE VIEW basketball_test.player_identity_aliases_v AS
SELECT
  m.game_id,
  m.game_year,
  m.team_id,
  m.source_player_id AS alias_player_id,
  m.canonical_player_id,
  COALESCE(NULLIF(btrim(m.player_name), ''), i.display_name) AS player_name,
  m.reason,
  m.scope AS correction_scope
FROM basketball_test.player_identity_map m
JOIN basketball_test.player_identities i
  ON i.identity_id = m.identity_id
WHERE m.active
  AND m.source_player_id <> m.canonical_player_id;

CREATE OR REPLACE VIEW basketball_test.resolved_player_identity_v AS
WITH roster_players AS (
  SELECT
    fr.game_id,
    fr.game_year,
    fr.team_id,
    fr.player_id AS source_player_id,
    max(NULLIF(btrim(concat_ws(' ', fr.firstname, fr.lastname)), '')) AS source_display_name
  FROM basketball_test.full_rosters fr
  WHERE fr.player_id IS NOT NULL
  GROUP BY fr.game_id, fr.game_year, fr.team_id, fr.player_id
),
roster_games AS (
  SELECT DISTINCT game_id, game_year, team_id
  FROM roster_players
),
mapped_source_players AS (
  SELECT
    m.game_id,
    m.game_year,
    m.team_id,
    m.source_player_id,
    m.player_name AS source_display_name
  FROM basketball_test.player_identity_map m
  WHERE m.active
    AND m.game_id IS NOT NULL

  UNION ALL

  SELECT
    rg.game_id,
    m.game_year,
    m.team_id,
    m.source_player_id,
    m.player_name AS source_display_name
  FROM basketball_test.player_identity_map m
  JOIN roster_games rg
    ON rg.game_year = m.game_year
   AND rg.team_id = m.team_id
  WHERE m.active
    AND m.game_id IS NULL
),
source_players AS (
  SELECT
    game_id,
    game_year,
    team_id,
    source_player_id,
    max(source_display_name) AS source_display_name
  FROM (
    SELECT * FROM roster_players
    UNION ALL
    SELECT * FROM mapped_source_players
  ) sp
  GROUP BY game_id, game_year, team_id, source_player_id
)
SELECT
  sp.game_id,
  sp.game_year,
  sp.team_id,
  sp.source_player_id,
  COALESCE(g.identity_id, y.identity_id, sp.source_player_id::bigint) AS identity_id,
  COALESCE(g.canonical_player_id, y.canonical_player_id, sp.source_player_id) AS canonical_player_id,
  COALESCE(ig.display_name, iy.display_name, sp.source_display_name) AS display_name,
  CASE
    WHEN g.map_id IS NOT NULL THEN 'game'
    WHEN y.map_id IS NOT NULL THEN 'season'
    ELSE 'source'
  END AS resolution_scope,
  COALESCE(g.reason, y.reason) AS reason
FROM source_players sp
LEFT JOIN basketball_test.player_identity_map g
  ON g.active
 AND g.provider = 'segev'
 AND g.game_id = sp.game_id
 AND g.team_id = sp.team_id
 AND g.source_player_id = sp.source_player_id
LEFT JOIN basketball_test.player_identities ig
  ON ig.identity_id = g.identity_id
LEFT JOIN basketball_test.player_identity_map y
  ON y.active
 AND y.provider = 'segev'
 AND y.game_id IS NULL
 AND y.game_year = sp.game_year
 AND y.team_id = sp.team_id
 AND y.source_player_id = sp.source_player_id
LEFT JOIN basketball_test.player_identities iy
  ON iy.identity_id = y.identity_id;
