-- Historical player shooting totals from basket.co.il's accumulated-stat pages.
--
-- This is an ETL/source layer only.  It deliberately does not change app-facing
-- tables or resolve identities automatically.

CREATE TABLE IF NOT EXISTS basketball_test.basket_shooting_import_runs (
  run_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requested_game_years integer[] NOT NULL,
  source_base_url text NOT NULL,
  parser_version text NOT NULL,
  status text NOT NULL CHECK (status IN ('running', 'completed', 'failed')),
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  requested_pages integer NOT NULL DEFAULT 0,
  fetched_pages integer NOT NULL DEFAULT 0,
  cache_hits integer NOT NULL DEFAULT 0 CHECK (cache_hits >= 0),
  parsed_rows integer NOT NULL DEFAULT 0,
  error_message text,
  CHECK ((status = 'running') = (finished_at IS NULL))
);

CREATE TABLE IF NOT EXISTS basketball_test.basket_shooting_source_pages (
  run_id bigint NOT NULL
    REFERENCES basketball_test.basket_shooting_import_runs(run_id),
  game_year integer NOT NULL CHECK (game_year BETWEEN 1990 AND 2100),
  page_number integer NOT NULL CHECK (page_number > 0),
  source_url text NOT NULL,
  content_md5 text NOT NULL CHECK (content_md5 ~ '^[0-9a-f]{32}$'),
  fetched_at timestamptz NOT NULL,
  cache_hit boolean NOT NULL DEFAULT false,
  parsed_rows integer NOT NULL CHECK (parsed_rows >= 0),
  PRIMARY KEY (run_id, game_year, page_number)
);

CREATE TABLE IF NOT EXISTS basketball_test.basket_player_season_shooting (
  game_year integer NOT NULL CHECK (game_year BETWEEN 1990 AND 2100),
  basket_player_id integer NOT NULL CHECK (basket_player_id > 0),
  player_name text NOT NULL CHECK (btrim(player_name) <> ''),
  games integer NOT NULL CHECK (games >= 0),
  minutes numeric,
  points numeric,
  fg2_made integer NOT NULL CHECK (fg2_made >= 0),
  fg2_attempted integer NOT NULL CHECK (fg2_attempted >= fg2_made),
  fg3_made integer NOT NULL CHECK (fg3_made >= 0),
  fg3_attempted integer NOT NULL CHECK (fg3_attempted >= fg3_made),
  ft_made integer NOT NULL CHECK (ft_made >= 0),
  ft_attempted integer NOT NULL CHECK (ft_attempted >= ft_made),
  source_url text NOT NULL,
  source_page integer NOT NULL CHECK (source_page > 0),
  source_row integer NOT NULL CHECK (source_row > 0),
  source_content_md5 text NOT NULL CHECK (source_content_md5 ~ '^[0-9a-f]{32}$'),
  fetched_at timestamptz NOT NULL,
  run_id bigint NOT NULL
    REFERENCES basketball_test.basket_shooting_import_runs(run_id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (game_year, basket_player_id),
  FOREIGN KEY (run_id, game_year, source_page)
    REFERENCES basketball_test.basket_shooting_source_pages
      (run_id, game_year, page_number)
);

CREATE INDEX IF NOT EXISTS basket_player_season_shooting_name_idx
  ON basketball_test.basket_player_season_shooting (game_year, lower(player_name));

-- Profile attributes are season-registration observations.  Keep them apart
-- from durable identity data: a player's listed position/height/nationality can
-- change or be corrected between registrations.
CREATE TABLE IF NOT EXISTS basketball_test.basket_player_season_profiles (
  game_year integer NOT NULL,
  basket_player_id integer NOT NULL,
  position_name text,
  height_m numeric CHECK (height_m BETWEEN 0.5 AND 3.0),
  nationality_name text,
  nationality_code text CHECK (
    nationality_code IS NULL OR nationality_code ~ '^[A-Z]{3}$'
  ),
  source_url text NOT NULL,
  source_content_md5 text NOT NULL CHECK (source_content_md5 ~ '^[0-9a-f]{32}$'),
  fetched_at timestamptz NOT NULL,
  cache_hit boolean NOT NULL DEFAULT false,
  run_id bigint NOT NULL
    REFERENCES basketball_test.basket_shooting_import_runs(run_id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (game_year, basket_player_id),
  FOREIGN KEY (game_year, basket_player_id)
    REFERENCES basketball_test.basket_player_season_shooting
      (game_year, basket_player_id),
  CHECK (position_name IS NOT NULL OR height_m IS NOT NULL OR nationality_name IS NOT NULL)
);

-- A Basket registration ID is not a durable person ID.  More than one proposed
-- identity may be retained, but only one verified mapping can be active.
CREATE TABLE IF NOT EXISTS basketball_test.basket_player_identity_map (
  game_year integer NOT NULL,
  basket_player_id integer NOT NULL,
  identity_id bigint NOT NULL
    REFERENCES basketball_test.player_identities(identity_id),
  review_status text NOT NULL DEFAULT 'candidate'
    CHECK (review_status IN ('candidate', 'verified', 'rejected')),
  match_method text NOT NULL
    CHECK (match_method IN ('same_season_source_id', 'profile_career_link',
                            'name_team_manual', 'manual')),
  confidence numeric CHECK (confidence BETWEEN 0 AND 1),
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  reviewer_notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (game_year, basket_player_id, identity_id),
  FOREIGN KEY (game_year, basket_player_id)
    REFERENCES basketball_test.basket_player_season_shooting
      (game_year, basket_player_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS basket_player_identity_one_verified_idx
  ON basketball_test.basket_player_identity_map (game_year, basket_player_id)
  WHERE review_status = 'verified';

CREATE INDEX IF NOT EXISTS basket_player_identity_identity_idx
  ON basketball_test.basket_player_identity_map (identity_id)
  WHERE review_status = 'verified';

-- Candidate evidence only.  Equal numeric IDs in the same season are useful,
-- but are not promoted into the mapping table without review.
CREATE OR REPLACE VIEW basketball_test.basket_player_identity_candidates_v AS
WITH pbp_candidates AS (
  SELECT DISTINCT
    game_year,
    source_player_id AS basket_player_id,
    identity_id,
    display_name
  FROM basketball_test.resolved_player_identity_v
), summarized AS (
  SELECT
    game_year,
    basket_player_id,
    count(*) AS candidate_count,
    min(identity_id) AS candidate_identity_id,
    min(display_name) AS candidate_display_name
  FROM pbp_candidates
  GROUP BY game_year, basket_player_id
)
SELECT
  s.game_year,
  s.basket_player_id,
  s.player_name AS basket_player_name,
  c.candidate_identity_id,
  c.candidate_display_name,
  COALESCE(c.candidate_count, 0) AS candidate_count,
  CASE
    WHEN c.candidate_count = 1 THEN 'same_season_source_id'
    WHEN c.candidate_count > 1 THEN 'ambiguous_source_id'
    ELSE 'no_source_id_match'
  END AS candidate_method,
  m.identity_id AS verified_identity_id
FROM basketball_test.basket_player_season_shooting s
LEFT JOIN summarized c
  USING (game_year, basket_player_id)
LEFT JOIN basketball_test.basket_player_identity_map m
  ON m.game_year = s.game_year
 AND m.basket_player_id = s.basket_player_id
 AND m.review_status = 'verified';

CREATE OR REPLACE VIEW basketball_test.basket_player_season_shooting_resolved_v AS
SELECT
  s.*,
  p.position_name,
  p.height_m,
  p.nationality_name,
  p.nationality_code,
  m.identity_id,
  i.display_name AS identity_display_name,
  (m.identity_id IS NOT NULL) AS identity_verified
FROM basketball_test.basket_player_season_shooting s
LEFT JOIN basketball_test.basket_player_season_profiles p
  USING (game_year, basket_player_id)
LEFT JOIN basketball_test.basket_player_identity_map m
  ON m.game_year = s.game_year
 AND m.basket_player_id = s.basket_player_id
 AND m.review_status = 'verified'
LEFT JOIN basketball_test.player_identities i
  ON i.identity_id = m.identity_id;

REVOKE ALL ON TABLE basketball_test.basket_shooting_import_runs FROM PUBLIC;
REVOKE ALL ON TABLE basketball_test.basket_shooting_source_pages FROM PUBLIC;
REVOKE ALL ON TABLE basketball_test.basket_player_season_shooting FROM PUBLIC;
REVOKE ALL ON TABLE basketball_test.basket_player_season_profiles FROM PUBLIC;
REVOKE ALL ON TABLE basketball_test.basket_player_identity_map FROM PUBLIC;
REVOKE ALL ON TABLE basketball_test.basket_player_identity_candidates_v FROM PUBLIC;
REVOKE ALL ON TABLE basketball_test.basket_player_season_shooting_resolved_v FROM PUBLIC;
