-- basketball_test.df_pts_poss_lineups_longer_mv source

CREATE or replace MATERIALIZED VIEW basketball_test.df_pts_poss_lineups_longer_mv
TABLESPACE pg_default
AS SELECT quarter,
    parameters_team,
    parameters_player,
    parameters_type,
    parameters_quarter,
    parameters_player_in,
    parameters_player_out,
    parameters_current_quarter,
    parameters_current_quarter_time,
    parameters_coord_x,
    parameters_coord_y,
    parameters_points,
    parameters_fast_break,
    parameters_second_chance_points,
    parameters_points_from_turnover,
    parameters_made,
    parameters_kind,
    parameters_fouled_on,
    parameters_free_throws,
    parameters_free_throws_awarded,
    parameters_free_throw_number,
    id,
    parent_action_id,
    user_time,
    quarter_time,
    type,
    player_id,
    team_id,
    score,
    total_player_points,
    game_id,
    end_quarter_seconds_remaining,
    end_game_seconds_remaining,
    parameters_is_coach_foul,
    parameters_is_bench_foul,
    row_num,
    pct_ft,
    q_bucket,
    team_score,
    end_poss,
    sum_poss_poss,
    sum_block,
    sum_tech,
    final_end_poss,
    final_start_seg,
    final_end_seg,
    segment_id,
    final_start_id,
    final_end_id,
    type_lineup,
    lineup_hash
   FROM ( SELECT pws.quarter,
            pws.parameters_team,
            pws.parameters_player,
            pws.parameters_type,
            pws.parameters_quarter,
            pws.parameters_player_in,
            pws.parameters_player_out,
            pws.parameters_current_quarter,
            pws.parameters_current_quarter_time,
            pws.parameters_coord_x,
            pws.parameters_coord_y,
            pws.parameters_points,
            pws.parameters_fast_break,
            pws.parameters_second_chance_points,
            pws.parameters_points_from_turnover,
            pws.parameters_made,
            pws.parameters_kind,
            pws.parameters_fouled_on,
            pws.parameters_free_throws,
            pws.parameters_free_throws_awarded,
            pws.parameters_free_throw_number,
            pws.id,
            pws.parent_action_id,
            pws.user_time,
            pws.quarter_time,
            pws.type,
            pws.player_id,
            pws.team_id,
            pws.score,
            pws.total_player_points,
            pws.game_id,
            pws.end_quarter_seconds_remaining,
            pws.end_game_seconds_remaining,
            pws.parameters_is_coach_foul,
            pws.parameters_is_bench_foul,
            pws.row_num,
            pws.pct_ft,
            pws.q_bucket,
            pws.team_score,
            pws.end_poss,
            pws.sum_poss_poss,
            pws.sum_block,
            pws.sum_tech,
            pws.final_end_poss,
            pws.final_start_seg,
            pws.final_end_seg,
            pws.segment_id,
            pws.final_start_id,
            pws.final_end_id,
            'offense'::text AS type_lineup,
            pws.lineup_hash_offense AS lineup_hash
           FROM pws
          WHERE pws.game_id <> ALL (ARRAY[62527, 62541, 62522])
        UNION ALL
         SELECT pws.quarter,
            pws.parameters_team,
            pws.parameters_player,
            pws.parameters_type,
            pws.parameters_quarter,
            pws.parameters_player_in,
            pws.parameters_player_out,
            pws.parameters_current_quarter,
            pws.parameters_current_quarter_time,
            pws.parameters_coord_x,
            pws.parameters_coord_y,
            pws.parameters_points,
            pws.parameters_fast_break,
            pws.parameters_second_chance_points,
            pws.parameters_points_from_turnover,
            pws.parameters_made,
            pws.parameters_kind,
            pws.parameters_fouled_on,
            pws.parameters_free_throws,
            pws.parameters_free_throws_awarded,
            pws.parameters_free_throw_number,
            pws.id,
            pws.parent_action_id,
            pws.user_time,
            pws.quarter_time,
            pws.type,
            pws.player_id,
            pws.team_id_defense,
            pws.score,
            pws.total_player_points,
            pws.game_id,
            pws.end_quarter_seconds_remaining,
            pws.end_game_seconds_remaining,
            pws.parameters_is_coach_foul,
            pws.parameters_is_bench_foul,
            pws.row_num,
            pws.pct_ft,
            pws.q_bucket,
            pws.team_score,
            pws.end_poss,
            pws.sum_poss_poss,
            pws.sum_block,
            pws.sum_tech,
            pws.final_end_poss,
            pws.final_start_seg,
            pws.final_end_seg,
            pws.segment_id,
            pws.final_start_id,
            pws.final_end_id,
            'defense'::text AS type_lineup,
            pws.lineup_hash_defense AS lineup_hash
           FROM pws
          WHERE pws.game_id <> ALL (ARRAY[62527, 62541, 62522])) longer
  WHERE lineup_hash IS NOT NULL
WITH DATA;

-- View indexes:
CREATE INDEX dfppl_game_id_idx ON basketball_test.df_pts_poss_lineups_longer_mv USING btree (game_id);
CREATE INDEX dfppl_lineup_game_cover_idx ON basketball_test.df_pts_poss_lineups_longer_mv USING btree (lineup_hash, game_id) INCLUDE (type_lineup, team_score, final_end_poss);
CREATE INDEX dfppl_lineup_hash_idx ON basketball_test.df_pts_poss_lineups_longer_mv USING btree (lineup_hash);
CREATE INDEX dfppl_mv_game_id_id_team ON basketball_test.df_pts_poss_lineups_longer_mv USING btree (game_id, id, team_id);
CREATE INDEX dfppl_mv_lineup_hash ON basketball_test.df_pts_poss_lineups_longer_mv USING btree (lineup_hash);
CREATE UNIQUE INDEX dfppl_mv_uq ON basketball_test.df_pts_poss_lineups_longer_mv USING btree (id, team_id, final_start_id, final_end_id, segment_id);
CREATE INDEX idx_df_longer_lineup_type ON basketball_test.df_pts_poss_lineups_longer_mv USING btree (lineup_hash, type_lineup);