# Stable player identity dictionary.
#
# This layer is additive: current ETL tables continue to store canonical
# provider player_id values. The dictionary resolves source IDs to a stable
# identity and exposes a compatibility view with the legacy alias shape.

assert_identity_schema_name <- function(schema) {
  if (!is.character(schema) || length(schema) != 1L ||
      !grepl("^[A-Za-z_][A-Za-z0-9_]*$", schema)) {
    stop("Invalid database schema name", call. = FALSE)
  }
  schema
}

player_identity_view_sql <- function(schema) {
  schema <- assert_identity_schema_name(schema)

  sprintf(
    'CREATE OR REPLACE VIEW "%1$s"."player_identity_aliases_v" AS
     SELECT
       m.game_id,
       m.game_year,
       m.team_id,
       m.source_player_id AS alias_player_id,
       m.canonical_player_id,
       COALESCE(NULLIF(btrim(m.player_name), \'\'), i.display_name) AS player_name,
       m.reason,
       m.scope AS correction_scope
     FROM "%1$s"."player_identity_map" m
     JOIN "%1$s"."player_identities" i
       ON i.identity_id = m.identity_id
     WHERE m.active
       AND m.source_player_id <> m.canonical_player_id',
    schema
  )
}

resolved_player_identity_view_sql <- function(schema) {
  schema <- assert_identity_schema_name(schema)

  sprintf(
    'CREATE OR REPLACE VIEW "%1$s"."resolved_player_identity_v" AS
     WITH roster_players AS (
       SELECT
         fr.game_id,
         fr.game_year,
         fr.team_id,
         fr.player_id AS source_player_id,
         max(NULLIF(btrim(concat_ws(\' \', fr.firstname, fr.lastname)), \'\')) AS source_display_name
       FROM "%1$s"."full_rosters" fr
       WHERE fr.player_id IS NOT NULL
       GROUP BY fr.game_id, fr.game_year, fr.team_id, fr.player_id
     ),
     roster_games AS (
       SELECT DISTINCT game_id, game_year, team_id
       FROM roster_players
     ),
     mapped_source_players AS (
       SELECT
         m.game_id,
         m.game_year,
         m.team_id,
         m.source_player_id,
         m.player_name AS source_display_name
       FROM "%1$s"."player_identity_map" m
       WHERE m.active
         AND m.game_id IS NOT NULL

       UNION ALL

       SELECT
         rg.game_id,
         m.game_year,
         m.team_id,
         m.source_player_id,
         m.player_name AS source_display_name
       FROM "%1$s"."player_identity_map" m
       JOIN roster_games rg
         ON rg.game_year = m.game_year
        AND rg.team_id = m.team_id
       WHERE m.active
         AND m.game_id IS NULL
     ),
     source_players AS (
       SELECT
         game_id,
         game_year,
         team_id,
         source_player_id,
         max(source_display_name) AS source_display_name
       FROM (
         SELECT * FROM roster_players
         UNION ALL
         SELECT * FROM mapped_source_players
       ) sp
       GROUP BY game_id, game_year, team_id, source_player_id
     )
     SELECT
       sp.game_id,
       sp.game_year,
       sp.team_id,
       sp.source_player_id,
       COALESCE(g.identity_id, y.identity_id, sp.source_player_id::bigint) AS identity_id,
       COALESCE(g.canonical_player_id, y.canonical_player_id, sp.source_player_id) AS canonical_player_id,
       COALESCE(ig.display_name, iy.display_name, sp.source_display_name) AS display_name,
       CASE
         WHEN g.map_id IS NOT NULL THEN \'game\'
         WHEN y.map_id IS NOT NULL THEN \'season\'
         ELSE \'source\'
       END AS resolution_scope,
       COALESCE(g.reason, y.reason) AS reason
     FROM source_players sp
     LEFT JOIN "%1$s"."player_identity_map" g
       ON g.active
      AND g.provider = \'segev\'
      AND g.game_id = sp.game_id
      AND g.team_id = sp.team_id
      AND g.source_player_id = sp.source_player_id
     LEFT JOIN "%1$s"."player_identities" ig
       ON ig.identity_id = g.identity_id
     LEFT JOIN "%1$s"."player_identity_map" y
       ON y.active
      AND y.provider = \'segev\'
      AND y.game_id IS NULL
      AND y.game_year = sp.game_year
      AND y.team_id = sp.team_id
      AND y.source_player_id = sp.source_player_id
     LEFT JOIN "%1$s"."player_identities" iy
       ON iy.identity_id = y.identity_id',
    schema
  )
}

ensure_player_identity_dictionary <- function(pg, schema = SCHEMA) {
  schema <- assert_identity_schema_name(schema)

  DBI::dbExecute(
    pg,
    sprintf(
      'CREATE TABLE IF NOT EXISTS "%s"."player_identities" (
         identity_id bigint GENERATED BY DEFAULT AS IDENTITY
           (START WITH 1000000000000) PRIMARY KEY,
         identity_key text NOT NULL UNIQUE,
         display_name text NOT NULL,
         first_name text,
         last_name text,
         first_name_local text,
         last_name_local text,
         notes text,
         created_at timestamptz NOT NULL DEFAULT now(),
         updated_at timestamptz NOT NULL DEFAULT now()
       )',
      schema
    )
  )

  DBI::dbExecute(
    pg,
    sprintf(
      'CREATE TABLE IF NOT EXISTS "%s"."player_identity_map" (
         map_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         provider text NOT NULL DEFAULT \'segev\',
         game_year int NOT NULL,
         team_id int NOT NULL,
         game_id int,
         source_player_id int NOT NULL,
         identity_id bigint NOT NULL
           REFERENCES "%s"."player_identities"(identity_id),
         canonical_player_id int NOT NULL,
         scope text NOT NULL CHECK (scope IN (\'season\', \'game\')),
         active boolean NOT NULL DEFAULT true,
         player_name text,
         reason text,
         evidence text,
         mapping_origin text NOT NULL DEFAULT \'manual\',
         created_at timestamptz NOT NULL DEFAULT now(),
         updated_at timestamptz NOT NULL DEFAULT now(),
         CHECK (
           (scope = \'season\' AND game_id IS NULL) OR
           (scope = \'game\' AND game_id IS NOT NULL)
         )
       )',
      schema, schema
    )
  )

  DBI::dbExecute(
    pg,
    sprintf(
      'CREATE UNIQUE INDEX IF NOT EXISTS player_identity_map_season_key
         ON "%s"."player_identity_map"
         (provider, game_year, team_id, source_player_id)
         WHERE game_id IS NULL',
      schema
    )
  )
  DBI::dbExecute(
    pg,
    sprintf(
      'CREATE UNIQUE INDEX IF NOT EXISTS player_identity_map_game_key
         ON "%s"."player_identity_map"
         (provider, game_id, team_id, source_player_id)
         WHERE game_id IS NOT NULL',
      schema
    )
  )
  DBI::dbExecute(
    pg,
    sprintf(
      'CREATE INDEX IF NOT EXISTS player_identity_map_identity_idx
         ON "%s"."player_identity_map" (identity_id)
         WHERE active',
      schema
    )
  )
  DBI::dbExecute(
    pg,
    sprintf(
      'CREATE INDEX IF NOT EXISTS player_identity_map_canonical_idx
         ON "%s"."player_identity_map"
         (provider, game_year, team_id, canonical_player_id)
         WHERE active',
      schema
    )
  )

  DBI::dbExecute(pg, player_identity_view_sql(schema))
  DBI::dbExecute(pg, resolved_player_identity_view_sql(schema))

  invisible(TRUE)
}

sync_player_identity_dictionary <- function(pg, schema = SCHEMA) {
  schema <- assert_identity_schema_name(schema)
  ensure_player_identity_dictionary(pg, schema)

  DBI::dbWithTransaction(pg, {
    # Create/update identities only from unambiguous roster contexts. The key
    # includes provider ID and normalized name so reused provider IDs do not
    # silently merge different people.
    DBI::dbExecute(
      pg,
      sprintf(
        'WITH roster_observations AS (
           SELECT
             fr.game_id,
             fr.game_year,
             fr.team_id,
             fr.player_id,
             CASE
               WHEN fr.player_id = 29543 THEN \'YARON GOLDMAN\'
               ELSE NULLIF(btrim(concat_ws(\' \', fr.firstname, fr.lastname)), \'\')
             END AS display_name,
             CASE
               WHEN fr.player_id = 29543 THEN \'YARON\'
               ELSE NULLIF(btrim(fr.firstname), \'\')
             END AS first_name,
             CASE
               WHEN fr.player_id = 29543 THEN \'GOLDMAN\'
               ELSE NULLIF(btrim(fr.lastname), \'\')
             END AS last_name,
             NULLIF(btrim(fr.firstnamelocal), \'\') AS first_name_local,
             NULLIF(btrim(fr.lastnamelocal), \'\') AS last_name_local,
             upper(
               regexp_replace(
                 regexp_replace(
                   CASE
                     WHEN fr.player_id = 29543 THEN \'YARON GOLDMAN\'
                     ELSE NULLIF(btrim(concat_ws(\' \', fr.firstname, fr.lastname)), \'\')
                   END,
                   \'\\.\\s+\',
                   \'.\',
                   \'g\'
                 ),
                 \'\\s+\',
                 \' \',
                 \'g\'
               )
             ) AS normalized_name
           FROM "%1$s"."full_rosters" fr
           WHERE fr.player_id IS NOT NULL
             AND NULLIF(btrim(concat_ws(\' \', fr.firstname, fr.lastname)), \'\') IS NOT NULL
         ),
         unambiguous_contexts AS (
           SELECT game_year, team_id, player_id
           FROM roster_observations
           GROUP BY game_year, team_id, player_id
           HAVING count(DISTINCT normalized_name) = 1
         ),
         identity_candidates AS (
           SELECT DISTINCT ON (
             \'segev:\' || ro.player_id::text || \':\' || ro.normalized_name
           )
             \'segev:\' || ro.player_id::text || \':\' || ro.normalized_name AS identity_key,
             ro.display_name,
             ro.first_name,
             ro.last_name,
             ro.first_name_local,
             ro.last_name_local
           FROM roster_observations ro
           JOIN unambiguous_contexts uc
             USING (game_year, team_id, player_id)
           ORDER BY
             \'segev:\' || ro.player_id::text || \':\' || ro.normalized_name,
             ro.game_year DESC,
             ro.game_id DESC
         )
         INSERT INTO "%1$s"."player_identities" (
           identity_key,
           display_name,
           first_name,
           last_name,
           first_name_local,
           last_name_local
         )
         SELECT
           identity_key,
           display_name,
           first_name,
           last_name,
           first_name_local,
           last_name_local
         FROM identity_candidates
         ON CONFLICT (identity_key) DO UPDATE
         SET display_name = EXCLUDED.display_name,
             first_name = COALESCE(EXCLUDED.first_name, "%1$s"."player_identities".first_name),
             last_name = COALESCE(EXCLUDED.last_name, "%1$s"."player_identities".last_name),
             first_name_local = COALESCE(EXCLUDED.first_name_local, "%1$s"."player_identities".first_name_local),
             last_name_local = COALESCE(EXCLUDED.last_name_local, "%1$s"."player_identities".last_name_local),
             updated_at = now()',
        schema
      )
    )

    # Add one season self-map per unambiguous team-season-provider ID.
    DBI::dbExecute(
      pg,
      sprintf(
        'WITH roster_observations AS (
           SELECT
             fr.game_year,
             fr.team_id,
             fr.player_id,
             CASE
               WHEN fr.player_id = 29543 THEN \'YARON GOLDMAN\'
               ELSE NULLIF(btrim(concat_ws(\' \', fr.firstname, fr.lastname)), \'\')
             END AS display_name,
             upper(
               regexp_replace(
                 regexp_replace(
                   CASE
                     WHEN fr.player_id = 29543 THEN \'YARON GOLDMAN\'
                     ELSE NULLIF(btrim(concat_ws(\' \', fr.firstname, fr.lastname)), \'\')
                   END,
                   \'\\.\\s+\',
                   \'.\',
                   \'g\'
                 ),
                 \'\\s+\',
                 \' \',
                 \'g\'
               )
             ) AS normalized_name
           FROM "%1$s"."full_rosters" fr
           WHERE fr.player_id IS NOT NULL
             AND NULLIF(btrim(concat_ws(\' \', fr.firstname, fr.lastname)), \'\') IS NOT NULL
         ),
         unambiguous AS (
           SELECT
             game_year,
             team_id,
             player_id,
             min(display_name) AS display_name,
             min(normalized_name) AS normalized_name
           FROM roster_observations
           GROUP BY game_year, team_id, player_id
           HAVING count(DISTINCT normalized_name) = 1
         )
         INSERT INTO "%1$s"."player_identity_map" (
           provider,
           game_year,
           team_id,
           game_id,
           source_player_id,
           identity_id,
           canonical_player_id,
           scope,
           active,
           player_name,
           reason,
           evidence,
           mapping_origin
         )
         SELECT
           \'segev\',
           u.game_year,
           u.team_id,
           NULL,
           u.player_id,
           i.identity_id,
           u.player_id,
           \'season\',
           true,
           u.display_name,
           \'unambiguous full_rosters identity\',
           \'generated from one normalized roster name for this team-season-player_id\',
           \'roster_self\'
         FROM unambiguous u
         JOIN "%1$s"."player_identities" i
           ON i.identity_key = \'segev:\' || u.player_id::text || \':\' || u.normalized_name
         ON CONFLICT (provider, game_year, team_id, source_player_id)
           WHERE game_id IS NULL
         DO UPDATE
         SET canonical_player_id = EXCLUDED.canonical_player_id,
             scope = EXCLUDED.scope,
             active = true,
             player_name = EXCLUDED.player_name,
             reason = EXCLUDED.reason,
             evidence = EXCLUDED.evidence,
             updated_at = now()
         WHERE "%1$s"."player_identity_map".mapping_origin = \'roster_self\'',
        schema
      )
    )

    DBI::dbExecute(
      pg,
      sprintf(
        'WITH roster_observations AS (
           SELECT
             fr.game_year,
             fr.team_id,
             fr.player_id,
             upper(
               regexp_replace(
                 regexp_replace(
                   CASE
                     WHEN fr.player_id = 29543 THEN \'YARON GOLDMAN\'
                     ELSE NULLIF(btrim(concat_ws(\' \', fr.firstname, fr.lastname)), \'\')
                   END,
                   \'\\.\\s+\',
                   \'.\',
                   \'g\'
                 ),
                 \'\\s+\',
                 \' \',
                 \'g\'
               )
             ) AS normalized_name
           FROM "%1$s"."full_rosters" fr
           WHERE fr.player_id IS NOT NULL
             AND NULLIF(btrim(concat_ws(\' \', fr.firstname, fr.lastname)), \'\') IS NOT NULL
         ),
         unambiguous AS (
           SELECT game_year, team_id, player_id
           FROM roster_observations
           GROUP BY game_year, team_id, player_id
           HAVING count(DISTINCT normalized_name) = 1
         )
         UPDATE "%1$s"."player_identity_map" m
         SET active = false,
             updated_at = now()
         WHERE m.mapping_origin = \'roster_self\'
           AND m.active
           AND NOT EXISTS (
             SELECT 1
             FROM unambiguous u
             WHERE u.game_year = m.game_year
               AND u.team_id = m.team_id
               AND u.player_id = m.source_player_id
           )',
        schema
      )
    )

    # Corrections normally target a roster self-map. Create a contextual
    # fallback identity only when the canonical roster identity is unavailable.
    DBI::dbExecute(
      pg,
      sprintf(
        'WITH corrections AS (
           SELECT
             game_year,
             team_id,
             canonical_player_id,
             max(NULLIF(btrim(player_name), \'\')) AS player_name
           FROM (
             SELECT game_year, team_id, canonical_player_id, player_name
             FROM "%1$s"."player_id_aliases"
             WHERE active
             UNION ALL
             SELECT game_year, team_id, canonical_player_id, player_name
             FROM "%1$s"."player_id_game_overrides"
             WHERE active
           ) c
           GROUP BY game_year, team_id, canonical_player_id
         )
         INSERT INTO "%1$s"."player_identities" (
           identity_key,
           display_name,
           notes
         )
         SELECT
           \'segev-context:\' || c.game_year::text || \':\' ||
             c.team_id::text || \':\' || c.canonical_player_id::text,
           COALESCE(c.player_name, \'PLAYER \' || c.canonical_player_id::text),
           \'Contextual identity created because no unambiguous canonical roster self-map was available\'
         FROM corrections c
         WHERE NOT EXISTS (
           SELECT 1
           FROM "%1$s"."player_identity_map" cm
           WHERE cm.active
             AND cm.provider = \'segev\'
             AND cm.game_id IS NULL
             AND cm.game_year = c.game_year
             AND cm.team_id = c.team_id
             AND cm.source_player_id = c.canonical_player_id
             AND cm.canonical_player_id = c.canonical_player_id
         )
         ON CONFLICT (identity_key) DO UPDATE
         SET display_name = EXCLUDED.display_name,
             updated_at = now()',
        schema
      )
    )

    DBI::dbExecute(
      pg,
      sprintf(
        'WITH corrections AS (
           SELECT
             NULL::int AS game_id,
             a.game_year,
             a.team_id,
             a.alias_player_id AS source_player_id,
             a.canonical_player_id,
             \'season\'::text AS scope,
             a.player_name,
             a.reason,
             \'legacy player_id_aliases row\'::text AS evidence,
             \'legacy_season_alias\'::text AS mapping_origin
           FROM "%1$s"."player_id_aliases" a
           WHERE a.active
         ),
         resolved AS (
           SELECT
             c.*,
             COALESCE(cm.identity_id, ci.identity_id) AS identity_id
           FROM corrections c
           LEFT JOIN "%1$s"."player_identity_map" cm
             ON cm.active
            AND cm.provider = \'segev\'
            AND cm.game_id IS NULL
            AND cm.game_year = c.game_year
            AND cm.team_id = c.team_id
            AND cm.source_player_id = c.canonical_player_id
            AND cm.canonical_player_id = c.canonical_player_id
           LEFT JOIN "%1$s"."player_identities" ci
             ON ci.identity_key = \'segev-context:\' || c.game_year::text || \':\' ||
               c.team_id::text || \':\' || c.canonical_player_id::text
         )
         INSERT INTO "%1$s"."player_identity_map" (
           provider,
           game_year,
           team_id,
           game_id,
           source_player_id,
           identity_id,
           canonical_player_id,
           scope,
           active,
           player_name,
           reason,
           evidence,
           mapping_origin
         )
         SELECT
           \'segev\',
           game_year,
           team_id,
           game_id,
           source_player_id,
           identity_id,
           canonical_player_id,
           scope,
           true,
           player_name,
           reason,
           evidence,
           mapping_origin
         FROM resolved
         WHERE identity_id IS NOT NULL
         ON CONFLICT (provider, game_year, team_id, source_player_id)
           WHERE game_id IS NULL
         DO UPDATE
         SET identity_id = EXCLUDED.identity_id,
             canonical_player_id = EXCLUDED.canonical_player_id,
             scope = EXCLUDED.scope,
             active = true,
             player_name = EXCLUDED.player_name,
             reason = EXCLUDED.reason,
             evidence = EXCLUDED.evidence,
             mapping_origin = EXCLUDED.mapping_origin,
             updated_at = now()',
        schema
      )
    )

    DBI::dbExecute(
      pg,
      sprintf(
        'WITH corrections AS (
           SELECT
             o.game_id,
             o.game_year,
             o.team_id,
             o.alias_player_id AS source_player_id,
             o.canonical_player_id,
             \'game\'::text AS scope,
             o.player_name,
             o.reason,
             \'legacy player_id_game_overrides row\'::text AS evidence,
             \'legacy_game_override\'::text AS mapping_origin
           FROM "%1$s"."player_id_game_overrides" o
           WHERE o.active
         ),
         resolved AS (
           SELECT
             c.*,
             COALESCE(cm.identity_id, ci.identity_id) AS identity_id
           FROM corrections c
           LEFT JOIN "%1$s"."player_identity_map" cm
             ON cm.active
            AND cm.provider = \'segev\'
            AND cm.game_id IS NULL
            AND cm.game_year = c.game_year
            AND cm.team_id = c.team_id
            AND cm.source_player_id = c.canonical_player_id
            AND cm.canonical_player_id = c.canonical_player_id
           LEFT JOIN "%1$s"."player_identities" ci
             ON ci.identity_key = \'segev-context:\' || c.game_year::text || \':\' ||
               c.team_id::text || \':\' || c.canonical_player_id::text
         )
         INSERT INTO "%1$s"."player_identity_map" (
           provider,
           game_year,
           team_id,
           game_id,
           source_player_id,
           identity_id,
           canonical_player_id,
           scope,
           active,
           player_name,
           reason,
           evidence,
           mapping_origin
         )
         SELECT
           \'segev\',
           game_year,
           team_id,
           game_id,
           source_player_id,
           identity_id,
           canonical_player_id,
           scope,
           true,
           player_name,
           reason,
           evidence,
           mapping_origin
         FROM resolved
         WHERE identity_id IS NOT NULL
         ON CONFLICT (provider, game_id, team_id, source_player_id)
           WHERE game_id IS NOT NULL
         DO UPDATE
         SET game_year = EXCLUDED.game_year,
             identity_id = EXCLUDED.identity_id,
             canonical_player_id = EXCLUDED.canonical_player_id,
             scope = EXCLUDED.scope,
             active = true,
             player_name = EXCLUDED.player_name,
             reason = EXCLUDED.reason,
             evidence = EXCLUDED.evidence,
             mapping_origin = EXCLUDED.mapping_origin,
             updated_at = now()',
        schema
      )
    )

    DBI::dbExecute(
      pg,
      sprintf(
        'UPDATE "%1$s"."player_identity_map" m
         SET active = false,
             updated_at = now()
         WHERE m.mapping_origin = \'legacy_season_alias\'
           AND m.active
           AND NOT EXISTS (
             SELECT 1
             FROM "%1$s"."player_id_aliases" a
             WHERE a.active
               AND a.game_year = m.game_year
               AND a.team_id = m.team_id
               AND a.alias_player_id = m.source_player_id
           )',
        schema
      )
    )
    DBI::dbExecute(
      pg,
      sprintf(
        'UPDATE "%1$s"."player_identity_map" m
         SET active = false,
             updated_at = now()
         WHERE m.mapping_origin = \'legacy_game_override\'
           AND m.active
           AND NOT EXISTS (
             SELECT 1
             FROM "%1$s"."player_id_game_overrides" o
             WHERE o.active
               AND o.game_id = m.game_id
               AND o.team_id = m.team_id
               AND o.alias_player_id = m.source_player_id
           )',
        schema
      )
    )
  })

  counts <- DBI::dbGetQuery(
    pg,
    sprintf(
      'SELECT
         (SELECT count(*) FROM "%1$s"."player_identities")::int AS identities,
         (SELECT count(*) FROM "%1$s"."player_identity_map" WHERE active)::int AS active_mappings,
         (SELECT count(*) FROM "%1$s"."player_identity_aliases_v")::int AS active_corrections',
      schema
    )
  )

  invisible(counts)
}

player_identity_ambiguity_summary <- function(pg, schema = SCHEMA) {
  schema <- assert_identity_schema_name(schema)
  ensure_player_identity_dictionary(pg, schema)

  DBI::dbGetQuery(
    pg,
    sprintf(
      'WITH problems AS (
         SELECT
           \'duplicate_active_season_mapping\'::text AS problem,
           NULL::int AS game_id,
           game_year,
           team_id,
           source_player_id,
           count(*)::int AS rows,
           NULL::text AS detail
         FROM "%1$s"."player_identity_map"
         WHERE active
           AND game_id IS NULL
         GROUP BY game_year, team_id, source_player_id
         HAVING count(*) > 1

         UNION ALL

         SELECT
           \'duplicate_active_game_mapping\'::text AS problem,
           game_id,
           max(game_year)::int AS game_year,
           team_id,
           source_player_id,
           count(*)::int AS rows,
           NULL::text AS detail
         FROM "%1$s"."player_identity_map"
         WHERE active
           AND game_id IS NOT NULL
         GROUP BY game_id, team_id, source_player_id
         HAVING count(*) > 1

         UNION ALL

         SELECT
           \'game_mapping_canonical_identity_conflict\'::text AS problem,
           g.game_id,
           g.game_year,
           g.team_id,
           g.source_player_id,
           1::int AS rows,
           \'game identity_id=\' || g.identity_id::text ||
             \', canonical season identity_id=\' || c.identity_id::text AS detail
         FROM "%1$s"."player_identity_map" g
         JOIN "%1$s"."player_identity_map" c
           ON c.active
          AND c.provider = g.provider
          AND c.game_id IS NULL
          AND c.game_year = g.game_year
          AND c.team_id = g.team_id
          AND c.source_player_id = g.canonical_player_id
          AND c.canonical_player_id = g.canonical_player_id
         WHERE g.active
           AND g.game_id IS NOT NULL
           AND g.identity_id <> c.identity_id

         UNION ALL

         SELECT
           \'active_legacy_correction_missing_from_compatibility_view\'::text AS problem,
           c.game_id,
           c.game_year,
           c.team_id,
           c.alias_player_id AS source_player_id,
           1::int AS rows,
           c.correction_scope || \' alias \' || c.alias_player_id::text ||
             \' -> \' || c.canonical_player_id::text AS detail
         FROM (
           SELECT
             NULL::int AS game_id,
             game_year,
             team_id,
             alias_player_id,
             canonical_player_id,
             \'season\'::text AS correction_scope
           FROM "%1$s"."player_id_aliases"
           WHERE active
           UNION ALL
           SELECT
             game_id,
             game_year,
             team_id,
             alias_player_id,
             canonical_player_id,
             \'game\'::text AS correction_scope
           FROM "%1$s"."player_id_game_overrides"
           WHERE active
         ) c
         LEFT JOIN "%1$s"."player_identity_aliases_v" v
           ON v.game_id IS NOT DISTINCT FROM c.game_id
          AND v.game_year = c.game_year
          AND v.team_id = c.team_id
          AND v.alias_player_id = c.alias_player_id
          AND v.canonical_player_id = c.canonical_player_id
          AND v.correction_scope = c.correction_scope
         WHERE v.alias_player_id IS NULL
       )
       SELECT *
       FROM problems
       ORDER BY problem, game_year, team_id, source_player_id, game_id',
      schema
    )
  )
}

player_identity_unresolved_summary <- function(pg, schema = SCHEMA, game_ids = NULL) {
  schema <- assert_identity_schema_name(schema)
  ensure_player_identity_dictionary(pg, schema)

  params <- list()
  game_filter <- ""
  if (!is.null(game_ids) && length(game_ids)) {
    game_ids <- sort(unique(as.integer(game_ids)))
    game_ids <- game_ids[is.finite(game_ids)]
    if (length(game_ids)) {
      game_filter <- "AND game_id = ANY($1::int[])"
      params <- list(sprintf("{%s}", paste(game_ids, collapse = ",")))
    }
  }

  sql <- sprintf(
    'SELECT
       game_year,
       team_id,
       source_player_id,
       count(DISTINCT game_id)::int AS games,
       string_agg(DISTINCT game_id::text, \',\' ORDER BY game_id::text) AS game_ids,
       max(display_name) AS display_name
     FROM "%s"."resolved_player_identity_v"
     WHERE resolution_scope = \'source\'
       %s
     GROUP BY game_year, team_id, source_player_id
     ORDER BY game_year, team_id, source_player_id',
    schema, game_filter
  )

  if (length(params)) {
    DBI::dbGetQuery(pg, sql, params = params)
  } else {
    DBI::dbGetQuery(pg, sql)
  }
}
